name = "quotes"
main = "src/index.ts"
compatibility_date = "2024-11-24"

[vars]
CLERK_PUBLISHABLE_KEY = "pk_test_Z2xhZC1ncnViLTMzLmNsZXJrLmFjY291bnRzLmRldiQ"
FRONTEND_URL = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "quotes"
database_id = "b9172042-d95d-4db3-872d-b28693cf4be9"

[observability]
enabled = true
head_sampling_rate = 1

[env.production.vars]
CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsucXVvdGVzLmZyYW5jaXNjb3NvbGlzLmNsJA"
FRONTEND_URL = "https://quotes.franciscosolis.cl"

[env.production.d1_databases]
binding = "DB"
database_name = "quotes"
database_id = "b9172042-d95d-4db3-872d-b28693cf4be9"